### PR TITLE
Add support for Unicode box drawing characters

### PR DESCRIPTION
**Pull request by gagern**
The ASCII lines can be hard to read under some circumstances. Using Unicode box drawing characters should on most terminals ensure that adjacent glyphs actually connect, leading to a smoother perception where lines and table content can be visually distinguished more easily.

### CODE REVIEW

**Comment by craigbox** [comment]
CP 437 says hello, and thank you.  
(I'm very keen to see this merged.)

**Comment by aaabramov** [comment]
Any chance this could be merged sometime?

**Comment by olekukonko** [comment]
@gagern I want to apologise for the very late response. 

1. can we have more test 
2. What if there are new set symbols, We may have some we support, but is it possible to also introduce flexibility in such a way a user can add a custom symbol table 

Regards

**Comment by gagern** [comment]
> 1. can we have more test

Sure. Anything specifically you'd like to see tested?

I've added some more test cases for basic functionality, including new support for footers which required some more work to get right. I also added Unicode variants of some existing test cases, even if in some of these the Unicode rendering isn't quite optimal yet. I added comments in these situations.

> 2. What if there are new set symbols, We may have some we support, but is it possible to also introduce flexibility in such a way a user can add a custom symbol table

Personally I would recommend letting the implementation gain a bit more maturity before opening it up further. The reason being that as long as this is fresh, there is a high chance things will move a bit so that any API added would become a burden to development. Once this has been stable for a bit, and particularly if there is concrete requests, then opening it up makes sense.

I'm also not sure what the most reasonable API would be. Would it make sense to expose the predefined order of characters, which currently is an implementation detail? Should we have one function invocation per character, with each call e.g. providing current symbol and the desired replacement? Or should we expose our `symbolID` constants and allow using them as keys in a map?

**Comment by olekukonko** [comment]
Can you take a look at https://github.com/olekukonko/tablewriter/pull/115,  it allows for flexible customisation can this  theme be incorporated in your proposal or did i merge too early ?

**Comment by craigbox** [comment]
@gagern [Or this](https://pbs.twimg.com/media/FHWRuM4UUAQkyzu.png) 😉

**Comment by olekukonko** [comment]
@gagern  Interesting,  when should we be expecting PR :)

**Comment by olekukonko** [comment]
@craigbox do you mind sharing more light?

**Comment by craigbox** [comment]
(I was just making a joke referring to the regular use of line-drawing characters in MS-DOS.)

**Pull request merged**
