### PR TITLE
add arbitrary separator on normal tables

### LINKED ISSUE #87: Allow arbitrary separators
It would be good if we allowed the insertion of arbitrary separators so that data in the table can be grouped.

### PR DESCRIPTION
**Pull request by guumaster**
This PR add a new function `AddSeparator()` so you can put arbitrary lines on tables.

#### Example
```go
data := [][]string{
    []string{"A", "The Good", "500"},
    []string{"B", "The Very very Bad Man", "288"},
    []string{"C", "The Ugly", "120"},
    []string{"D", "The Gopher", "800"},
}

table := tablewriter.NewWriter(os.Stdout)
table.SetHeader([]string{"Name", "Sign", "Rating"})

for i, v := range data {
    table.Append(v)
    // Add separator after row "B"
	if i == 1 {
        table.AddSeparator()
    }
}
table.Render() // Send output
```

##### Output  7
```
+------+-----------------------+--------+
| NAME |         SIGN          | RATING |
+------+-----------------------+--------+
|  A   |       The Good        |    500 |
|  B   | The Very very Bad Man |    288 |
+------+-----------------------+--------+
|  C   |       The Ugly        |    120 |
|  D   |      The Gopher       |    800 |
+------+-----------------------+--------+
```

~~*Note*: it only work with not merged tables. I tried with `SetAutoMergeCells` but couldn't make it work.~~ now it works!

If this take long to merge, you can install the fork with `go get github.com/guumaster/tablewriter@v0.0.9` to use this feature.

Closes #87

### CODE REVIEW

**Comment by guumaster** [comment]
Merged new master features. 

Would this PR be considered at some point?

Thanks

**Comment by olekukonko** [comment]
@guumaster can you resolve conflicts?

**Comment by olekukonko** [comment]
@ guumaster ping

**Comment by guumaster** [comment]
@olekukonko done! :rocket:

**Comment by guumaster** [comment]
@olekukonko ping :wink:

**Comment by guumaster** [comment]
@olekukonko I've updated my fork and also this PR with the hope that it could be merged. Thanks!

**Pull request closed without merging**
