### PR TITLE
Fix WrapWords excessive memory utilization

### PR DESCRIPTION
**Pull request by horkhe**
When feeding production data to this library we discovered that function `WordWrap` had O(n*n) memory complexity, that resulted in huge amounts of memory allocated when processing even relatively small strings. We are talking Gigabytes that made our production services killed with OOM. This PR implements 2 optimisations:
* Function `splitWords` was introduced to efficiently break a line into words. Note that unlike original implementation it does not consider empty spaces to be words.
* Function `WrapWords` was rewritten to be O(n) on memory complexity. A benchmark that comes with this PR shows great improvement:
```
BenchmarkWrapString-16
Before:     1	2490331031 ns/op	2535184104 B/op	50905550 allocs/op
After:   1652	    658098 ns/op	    230223 B/op	    5176 allocs/op
```

### CODE REVIEW

**Comment by horkhe** [comment]
@olekukonko any chance to get this PR looked at?

**Comment by olekukonko** [comment]
@horkhe  sorry for the late response, this is wonderful, will take my time to look at this next week so that it can be merged

**Comment by olekukonko** [comment]
@horkhe  can you kindly update your PR and resolve merge conflicts, I Would really like to merge this performance improvement. thank you

**Comment by horkhe** [comment]
@olekukonko sorry for late response. I have rebased this PR.

**Comment by horkhe** [comment]
@olekukonko any change to get this merged?

**Comment by horkhe** [comment]
@olekukonko any chance to get this merged?

**Comment by olekukonko** [comment]
@horkhe  will look at this this weekend and revert. Thank you for being consistent.

**Comment by horkhe** [comment]
@olekukonko a friendly reminder.

**Comment by horkhe** [comment]
Thanks a lot! Could you please also tag the master with v0.0.6, so it can be picked up by `go mod`.

**Pull request merged**
