### PR TITLE
color table content added

### PR DESCRIPTION
**Pull request by iammehrabalam**
Now we can color text of table

### CODE REVIEW

**Comment by olekukonko** [comment]
Have you tested this on windows ?? It does not work

**Comment by iammehrabalam** [comment]
No  only tested on Linux

**Comment by olekukonko** [comment]
We need to look for ways to test this on windows before merge

**Comment by mattn** [comment]
you can use https://github.com/mattn/go-colorable 

```go
table := NewWriter(colorable.NewColorableStdout())
```

**Comment by olekukonko** [comment]
@mattn can you set each `column & row` with a different color with `colorable.NewColorableStdout()`

**Comment by mattn** [comment]
This PR is merged with some small fixes. https://github.com/olekukonko/tablewriter/pull/70

Thank you!

**Pull request closed without merging**
