### PR TITLE
Remove call to math.Ceil.

### PR DESCRIPTION
**Pull request by bogosj**
https://staticcheck.io/docs/checks#SA4015

### CODE REVIEW

**Comment by dominikh** [comment]
Note that `int(float64(gap / 2))` is the same as `int(gap / 2)` which is the same as `gap / 2`. Are you sure you didn't mean `float64(gap) / 2`? `int(math.Ceil(float64(gap) / 2))` would actually make sense.

**Comment by bogosj** [comment]
I'm unclear on the original intent of this code, but as it stands this change is functionally equivalent, because gap was an int to begin with:
https://play.golang.org/p/t0NQcqB6oga

You're correct that this could be further simplified down to `gap / 2` and it would preserve the functionality as it exists. I'm happy to adjust accordingly.

**Comment by bogosj** [comment]
Playground with `gap / 2` included: https://play.golang.org/p/dYeDpKaaoSU

**Comment by olekukonko** [comment]
@mattn ping

**Pull request closed without merging**
