### PR TITLE
Allow to choose the alignment of the header and footer

### LINKED ISSUE #29: Left or Right-aligned Headers
I noticed that that the headers are only CENTERED-aligned.
I want to be able to LEFT-aligned my headers. How do I do that?
Even if I set t.SetAutoFormatHeaders(false), its still CENTER-aligned.

### PR DESCRIPTION
**Pull request by Thiht**
Fix #29

### CODE REVIEW

**Comment by olekukonko** [comment]
Hello ... thanks for the contribution ... `padFunc` is duplicated, since it is used by `printHeading` & `printFooter`  think we can make it a private function  ...

**Comment by Thiht** [comment]
Do you prefer something like:

```go
// return the correct pad function
func pad(align int) func(string, string, int) string {
	padFunc := Pad
	switch align {
	case ALIGN_LEFT:
		padFunc = PadRight
	case ALIGN_RIGHT:
		padFunc = PadLeft
	}
	return padFunc
}
```
or something like:

```go
// helper pad
func pad(text string, width, align int) string {
	padFunc := Pad
	switch align {
	case ALIGN_LEFT:
		padFunc = PadRight
	case ALIGN_RIGHT:
		padFunc = PadLeft
	}
	return padFunc(text, SPACE, width)
}
```
The second one is clearer because it doesn't return a function, but it's called in a loop so it's wasted resources. I personally prefer the first one but it's your call. I'll update the PR as soon as I have your answer, thanks for the reactivity

**Comment by olekukonko** [comment]
Sorry for the late response .... I also prefer the first one ....  Thanks for the contribution ....

**Comment by Thiht** [comment]
I did the modification

**Pull request merged**
