### PR TITLE
Allow caption functionality for table

### PR DESCRIPTION
**Pull request by hasit**
#### Example - Set table caption

``` go
data := [][]string{
    []string{"A", "The Good", "500"},
    []string{"B", "The Very very Bad Man", "288"},
    []string{"C", "The Ugly", "120"},
    []string{"D", "The Gopher", "800"},
}

table := tablewriter.NewWriter(os.Stdout)
table.SetHeader([]string{"Name", "Sign", "Rating"})
table.SetCaption(true, "Movie ratings.")

for _, v := range data {
    table.Append(v)
}
table.Render() // Send output
```

Note: Caption text will wrap with total width of rendered table.
##### Output

```
+------+-----------------------+--------+
| NAME |         SIGN          | RATING |
+------+-----------------------+--------+
|  A   |       The Good        |    500 |
|  B   | The Very very Bad Man |    288 |
|  C   |       The Ugly        |    120 |
|  D   |      The Gopher       |    800 |
+------+-----------------------+--------+
Movie ratings.
```

### CODE REVIEW

**Comment by olekukonko** [comment]
Hello, Thanks for the contribution ....  I have some questions 

- Can you resolve the merge conflicts
- How does this work with footer 
- Would there be option for alignment ...

**Comment by hasit** [comment]
Hello @olekukonko,

I would like to apologize for the long delay in reply.
- I have resolved the merge conflict. 
- It plays well with footer. While footer is a part of the table, caption lives right below the table.
```
+--------+-----------------------+--------+
|  NAME  |         SIGN          | RATING |
+--------+-----------------------+--------+
| A      | The Good              |    500 |
| B      | The Very very Bad Man |    288 |
| C      | The Ugly              |    120 |
| D      | The Gopher            |    800 |
+--------+-----------------------+--------+
| FOOTER |        SCOOTER        |  900   |
+--------+-----------------------+--------+
This is long  caption. Let's see how it fits
below a narrow table. Let me try to increase
the length by a little more.
```
- I am planning to add alignment option soon. Mostly just left and right alignment.

What are you thoughts on this? Let me know if you think of any other functionality to add to captioning.

**Comment by olekukonko** [comment]
Hello,

Thanks for the update ..... can you please 

1. How you display the caption in this type of table 


```txt


    DATE   |       DESCRIPTION        |  CV2  | AMOUNT
+----------+--------------------------+-------+---------+
  1/1/2014 | Domain name              |  2233 | $10.98
  1/1/2014 | January Hosting          |  2233 | $54.95
  1/4/2014 | February Hosting         |  2233 | $51.00
  1/4/2014 | February Extra Bandwidth |  2233 | $30.00
+----------+--------------------------+-------+---------+
                                        TOTAL | $146 93
                                      +-------+---------+

```

2. Can you also add a test  to this types of table.

Regards
Oleku

**Comment by hasit** [comment]
A quick question - is there a way to retrieve total width of the table? That would be very helpful.

**Comment by olekukonko** [comment]
Thai is very tricky .... we need to sum all the values of `t.cs` and add it to `3 * number of cols`  the 3 would compensate for the padding ...  take a look at `parseDimension` and see how the we store each row width

**Comment by hasit** [comment]
@olekukonko,

I have added a test as you requested. Also, I made a new function called getTableWidth() for future easy calculation of width.

**Comment by hasit** [comment]
This is how it looks with footer and no border.
screen shot 2016-07-29 at 11 41 22 am

**Comment by hasit** [comment]
@olekukonko 

I have resolved merge conflicts. Please do review and let me know if any changes are required.

**Comment by olekukonko** [comment]
Hello sorry for the late response ... I still see merge request ?

**Comment by mattn** [comment]
Closed by #72

**Pull request closed without merging**
