### PR TITLE
add parse-from-html

### PR DESCRIPTION
**Pull request by chyroc**

### CODE REVIEW

**Comment by olekukonko** [comment]
This has been on my todo list for a long time but I have reservations using dependent management in a library and not the application. 

Introduction of gopkg.in may not be a good idea. 

@mattn  what do you think?

**Comment by mattn** [comment]
Seems good to me. BTW, Do this works with use colspan/rowspan? And when the HTML have two table tag, how works this?

**Comment by Chyroc** [comment]
Does the tablewriter support colspan/rowspan, I didn't find it in the code, maybe should support this in tablewriter first, and then complete this pr

If an html contains two tables, I think it should print two tables, separated by a blank line

**Comment by olekukonko** [comment]
@Chyroc are you rebase and add more test, I see good value in this PR.

**Comment by olekukonko** [comment]
@chyroc apologies for the late response, sorry for the inconvenience. Can you please once again resolve the merge conflicts

**Pull request closed without merging**
