### PR TITLE
 Add poweron architecture ppc64le to travis build

### PR DESCRIPTION
**Pull request by asellappen**
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,For more info tag @gerrith3.

### CODE REVIEW

**Comment by asellappen** [comment]
any updates on this pls

**Comment by olekukonko** [comment]
@mattn ping

**Comment by asellappen** [comment]
@mattn ,Please help to validate the changes and merge

**Comment by mattn** [comment]
Ooops. Sorry, I did not notice mentioned. Will look soon.

**Comment by mattn** [comment]
Seem good to me. BTW, why this PR is not tested on travis.

**Comment by asellappen** [comment]
It was ran on travis as below ,but not tagged here,
https://travis-ci.com/github/asellappen/tablewriter/jobs/400261602

**Comment by mattn** [comment]
LGTM. Thank you.

**Comment by asellappen** [comment]
Thank you Mattn-san

**Pull request merged**
